--DROP EXISTING TABLES
DROP TABLE IF EXISTS W_ERROR_LOG;
DROP TABLE IF EXISTS W_JOB_CHANGE_DATA;

--DROP EXISTING SEQUENCES
DROP SEQUENCE IF EXISTS W_JOB_SEQ;
DROP SEQUENCE IF EXISTS W_ERROR_LOG_SEQ;

--CREATE SEQUENCES
CREATE SEQUENCE W_Job_Seq START WITH 1000000 INCREMENT BY 1;
CREATE SEQUENCE W_Error_Log_Seq START WITH 1 INCREMENT BY 1;

-- create tables…

/*********************************
    W_JOB_CHANGE_DATA
**********************************/  
CREATE TABLE W_JOB_CHANGE_DATA
(
	CHANGE_ID 			INTEGER NOT NULL, 
	CONTRACT_DATE 		CHAR(10), 
	SALES_AGENT_ID 		INTEGER, 
	SALES_CLASS_ID 		INTEGER, 
	LOCATION_ID 		INTEGER, 
	CUST_ID_ORDERED_BY 	INTEGER, 
	DATE_PROMISED 		CHAR(10), 
	DATE_SHIP_BY 		CHAR(10), 
	NUMBER_OF_SUBJOBS 	INTEGER, 
	UNIT_PRICE 			DECIMAL(5,2), 
	QUANTITY_ORDERED 	INTEGER, 
	QUOTE_QTY 			INTEGER, 
	LEAD_ID 			INTEGER, 
	CONSTRAINT W_JOB_CHANGE_DATA_PK PRIMARY KEY (CHANGE_ID)
);

/*********************************
    W_ERROR_LOG
**********************************/ 
CREATE TABLE W_ERROR_LOG
(
	Log_Id		INTEGER NOT NULL,
	Change_Id	INTEGER,
	Job_Id		INTEGER,
	Note		VARCHAR(200),
	CONSTRAINT W_ERROR_LOG_PK PRIMARY KEY (Log_Id),
    CONSTRAINT W_ERROR_LOG_CHANGE_ID_FK FOREIGN KEY (CHANGE_ID) REFERENCES W_JOB_CHANGE_DATA (CHANGE_ID)
);